CREATE TABLE IF NOT EXISTS CURL_ACTIVITY (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CREATED_AT TIMESTAMP NOT NULL,
    ENVIRONMENT VARCHAR(20) NOT NULL,
    SERVICE_NAME VARCHAR(50) NOT NULL,
    COMMAND TEXT NOT NULL
)