CREATE TABLE IF NOT EXISTS ROUTINE_CHECKS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CREATED_AT TIMESTAMP NOT NULL,
    RUN_AT TIMESTAMP NOT NULL,
    STATUS VARCHAR(15) NOT NULL,
    PROGRAM VARCHAR(50) NOT NULL
)